# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ecf587ab7252b6c95004fff61d88b03d7b8bd399ea5533a57c5e6856c93fb4fd285e372982bf4bffee92b8cb81beb9278e40adc830d78d67615675c3dcd477e

test:
  secret_key_base: 5fc7b62f5ae8346d4bd50cbbf97780e66c4dff5b751fc201f029d73d89d1201e71de6ec2cd53a95e2016ac73c5a3f6867f8a0849c86ae1c4073373e0b5edce20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
